### ISSUE TITLE
utc-0.1.0.0 test suite failure

### ISSUE THREAD

**Issue by peti** [lpeterse/tempus#1]
Please see http://hydra.cryp.to/build/778539/log/raw for a complete log of the failing build.

**Comment by lpeterse** [comment]
Thanks for the report. I can confirm there's an error and I'm working on it.

**Comment by lpeterse** [comment]
The corresponding test itself is wrong. It fails on year boundaries, because the general assumption that a year has 366 days is wrong:

``` haskell
testYearToDaysAndDaysToYear :: Test
testYearToDaysAndDaysToYear
  = testGroup "yearToDays <-> daysToYear"
  $ [ testProperty "yearToDays (daysToYear x) - x === 0"
    $ forAll (choose (0, 146463))
    $ \x-> (x - yearToDays (daysToYear x)) `div` 366 === 0
    ]
```

**Comment by lpeterse** [comment]
I removed the test. I consider the remaining tests (the explicit ones I wrote later) to be sufficient: They subsume the properties of the removed one.
